spring:
  application:
    name: smoker
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          # 카카오
          kakao:
            client-authentication-method: client_secret_post
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
          # 구글
          google:
            client-id:
            client-secret:
            scope:
              - profile
              - email
              -
        # kakao provider 설정
        provider:
          kakao:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute: